### ISSUE TITLE
SwitchBot Bot exposed as outlet

### ISSUE THREAD

**Issue by SimonLawson70** [OpenWonderLabs/homebridge-switchbot-openapi#102]
The SwitchBot Bot is exposed in the Home app as a power outlet, not a switch.

**To Reproduce:**

1. Installed SwitchBot OpenAPI plugin
2. Logged in with Developer Token
3. In the iOS 14 Home app, my SwitchBot Bot is exposed as an outlet

I expected the SwitchBot to be a switch!

**Logs:**

{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "*****",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "bot": {
                    "device_switch": [
                        "F53BC95303D9"
                    ]
                },
                "meter": {
                    "unit": 0
                }
            }

**Screenshots:**

**Device Model:**

SwitchBot S1 

# **Environment:**

- **Node.js Version**: 14.15.4
- **NPM Version**: 6.14.10
- **Homebridge Version**: 1.3.0 beta 56
- **Homebridge SwitchBot Plugin Version**: 2.4.0
- **Homebridge Config UI X Plugin Version**: 4.38.0
- **Operating System**: Docker (Synology DSM)

**Comment by donavanbecker** [comment]
https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/releases/tag/v2.3.0

**Comment by donavanbecker** [comment]
I displayed it as outlet because you have 3 different devices you can set it as: outlet, light, fan.

With switch you only have 1
