### ISSUE TITLE
After updating to the current version 3.0.1,  the Bots no longer works

### ISSUE THREAD

**Issue by MikeDeltaHH** [OpenWonderLabs/homebridge-switchbot-openapi#104]
With version 2.40 all my three switchbots work, when I update to version 3.x and activate a bot nothing happens - in the Homebridge log nothing is displayed as if Homebridge would not notice that at all! Only the humidifier continues to work! If I go back to version 2.4 the bots work again!

I have activated the Developer Mode and operated the bots several times, but no entry is generated in the log! My bots are configured in Press Mode - if I press one so it is displayed in version 2.4 briefly as on and then goes off again so - in version 3.x the bot remains on on, no matter what I enter in the Refresh Rate for a value!

[homebridge.log.txt](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/files/5975321/homebridge.log.txt)

**Homebridge Config:**

[config.json.txt](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/files/5975332/config.json.txt)

**Device Model:**

ESXi virtual machine

# **Environment:**

- **Node.js Version**: v14.15.4 
- **NPM Version**: v7.5.2 
- **Homebridge Version**: 1.2.5
- **Homebridge SwitchBot Plugin Version**: 3.0.1
- **Homebridge Config UI X Plugin Version**: v4.38.0 
- **Operating System**:  Ubuntu 20.04 LTS

**Comment by DJay-X** [comment]
Same here. Just updated to 3.0.1 and Bots are not responding anymore. Nothing to see in the Log.
Curtains however still work. 
homebridge@1.2.5 | node@14.15.5 | npm 7.5.3 | n@7.0.0 | switchbot-openapi@3.0.1

```
{
            "name": "SwitchBotAPI",
            "credentials": {
                "openToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "bot": {
                    "device_press": [
                        "EEC09XXXXXXX",
                        "DD82FXXXXXXX",
                        "CC368XXXXXXX",
                        "C46F2XXXXXXX",
                        "D035AXXXXXXX"
                    ]
                }
            },
            "platform": "SwitchBot"
        }
```

**Comment by donavanbecker** [comment]
Have an idea of what it is, so give me a little bit and I will have a fix out.

**Comment by donavanbecker** [comment]
@DJay-X @MikeDeltaHH 

[v3.0.2](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/releases/tag/v3.0.2) is release and should fix this.

**Comment by MikeDeltaHH** [comment]
Yes, ist works again! Thanks for the fast support and have a nice weekend!

**Comment by donavanbecker** [comment]
@MikeDeltaHH No problem! If you have curtains and are willing to test the latest beta, check out #17

**Comment by MikeDeltaHH** [comment]
Thanks - at the moment i haven‘t any courtains but these are on my list for the next time! 😁
