### ISSUE TITLE
Renaming SwitchBot Curtain adds newly-named device but keeps other devices with older name

### ISSUE THREAD

**Issue by antoniogermano** [OpenWonderLabs/homebridge-switchbot-openapi#107]
**Describe the issue:**
Renaming a device on the SwitchBot app adds the new device on HomeKit but does not remove the previous device. There's also no way that I've found to remove the old device.

**To Reproduce:**
This assumes you have a SwitchBot curtain already configured on the SwitchBot iOS app and on Homebridge using the homebridge-switchbot-openapi plugin. I only have a total of 2 curtains.

- Open the SwitchBot app.
- Tap Curtain 1.
- Rename it to New Curtain Name.
- Restart Homebridge.

**Expected behavior:**
The Curtain 1 device would disappear from HomeKit, and the New Curtain Name device would appear.

**What actually happened:**
The Curtain 1 device remains on HomeKit. The New Curtain Name was added. It now shows I have 3 curtains.

**Logs:**

```
[2/13/2021, 9:30:28 PM] [SwitchBot Hub] Loading accessory from cache: Curtain Living Room 2 Curtain
[2/13/2021, 9:30:28 PM] [SwitchBot Hub] Loading accessory from cache: Living Room Curtain
[2/13/2021, 9:30:29 PM] [SwitchBot Hub] Total SwitchBot Devices Found: 3 # but I only have 2!
[2/13/2021, 9:30:29 PM] [SwitchBot Hub] Total IR Devices Found: 0
[2/13/2021, 9:30:29 PM] [SwitchBot Hub] Restoring existing accessory from cache: Curtain 1 Curtain DeviceID: <redacted1>
[2/13/2021, 9:30:29 PM] [SwitchBot Hub] Adding new accessory: New Curtain Name Curtain DeviceID: <redacted2>
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "USERNAME",
        "port": PORT,
        "pin": "PIN"
    },
    "accessories": [
        {
            "accessory": "LinuxTemperature",
            "name": "Server CPU",
            "sensor_path": "/Users/antoniogermano/.cpu_temp",
            "divisor": 1
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": PORT,
            "platform": "config"
        },
        {
            "name": "EMAIL",
            "credentials": {
                "openToken": "TOKEN",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
    ]
}
```

**Screenshots:**

**Device Model:**

ChatBot Curtain

# **Environment:**

- **Node.js Version**: v12.18.3
- **NPM Version**: v6.14.6
- **Homebridge Version**: v1.2.5
- **Homebridge SwitchBot Plugin Version**: homebridge-switchbot-openapi v3.0.2
- **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.38.0
- **Operating System**: macOS Big Sur 11.2.1 (20D74)

**Comment by donavanbecker** [comment]
The universally unique identifier (UUID) of any device that is added through the SwitchBot plugin is created based off of the deviceId, device name and device type so that no matter what this combination would always be unique. 

To remove the left over curtains there is a setting in Homebridge UI that allows you to remove individual accessories from the accessory cache. This how you can remove the left over curtain from you renaming the curtain.

**Comment by donavanbecker** [comment]
if you need more help feel free to reach out on the [homebridge discord server](https://discord.gg/5wYTbwP4ha).

**Comment by erwinloh** [comment]
I have the same problem actually - how do you get rid of the old device without resetting everything?

**Comment by donavanbecker** [comment]
@erwinloh do you have Homebridge UI? if so you can clear cache on just the 1 extra accessory.
<a><img src="https://user-images.githubusercontent.com/9875439/108710389-99ae6300-74d9-11eb-93c1-8401b9d0a372.png" width="800px"></a>
