### ISSUE TITLE
hide „temperatur“ mode Humidifier

### ISSUE THREAD

**Issue by Kohle81** [OpenWonderLabs/homebridge-switchbot-openapi#108]
I am on version v3.0.2 and I want to hide temperature sensor of Humidifier.

Here is my config part:

"humidifier": {
					"hide_temperature": true,
					"set_minStep": 20
				}
				
But in homekit the sensor is shown. I have deleted the cache snd restarted Homekit - sensor is there in Homekit.

Would it addition be possible to hide the temperature sensor and the humidity level from the humidifier in Homekit?

When the Switch Meter is used the Humidity Level from the Humidifier would not be used.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
@Kohle81 I will look into this.
