### ISSUE TITLE
Meter temperature sensor no response once below 0

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-openapi#115]
Meter temperature sensor shows No Response once below zero.

**To Reproduce:**
Put the sensor somewhere below 0 Celsius.

**Expected behavior:**
Home app SwitchBot meter temperature sensor No Response. 

**Logs:**
No logs

**Homebridge Config:**

 {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 1200,
                "hide_device": [
                    "E416FECFBDEC",
                    "DC36EAA29B0F"
                ],
                "curtain": {
                    "set_minStep": 5,
                    "set_min": 2,
                    "set_max": 98
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        }

**Screenshots:**
<a><img src="https://user-images.githubusercontent.com/48269361/108274208-ce18cc80-7131-11eb-8d2f-3f698731cdcb.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/48269361/108274386-0ddfb400-7132-11eb-927b-c6243a8fb7ca.png" width="250px"></a>
<a><img src="https://user-images.githubusercontent.com/48269361/108274526-3ff11600-7132-11eb-8d0f-b2fc59bcc122.png" width="250px"></a>

**Device Model:**
Raspberry Pi 3

# **Environment:**

- **Node.js Version**: v14.15.5
- **NPM Version**: v7.5.4
- **Homebridge Version**: v1.1.7
- **Homebridge SwitchBot Plugin Version**:v3.1.0
- **Homebridge Config UI X Plugin Version**:v4.39.0
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@jonpeng, had a chance to look at this. hoping the latest beta will fix this for you.
Can you test it out?

Beta: `v3.1.1-beta.12`

**Comment by donavanbecker** [comment]
should be fixed with v3.2.0, if not please open new issue.

**Comment by jonpeng** [comment]
@donavanbecker 
v3.2.0 fixed.
