### ISSUE TITLE
Duplicate device after renaming in the Switchbot app

### ISSUE THREAD

**Issue by erwinloh** [OpenWonderLabs/homebridge-switchbot-openapi#121]
As described, in current version of plugin.

In Switchbot app, I rename a switch bot.

The new name appears in Home app, but the old name remains.

Both the devices have same Mac address.

How do I get rid of the original bot from Home app?

**Comment by donavanbecker** [comment]
@erwinloh FYI, you can't change anything on the template or it will auto close, this is to prevent spam. I will reopen.

**Comment by erwinloh** [comment]
Hi @donavanbecker thanks for reopening - you may recall I use Hoobs, so there's no such option. I've resynced everything and it's fine now.

Is there a method of renaming devices in Switchbot that avoids this issue? Like shutting down the homebridge service, rename, and turning it back on?

**Comment by donavanbecker** [comment]
@erwinloh No there isn't. If you rename you will have to do what you did. Or switch to Homebridge which makes it way easier to manage your devices.

**Comment by erwinloh** [comment]
Ok, thanks for the prompt response.
