### ISSUE TITLE
IR devices name change

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-openapi#122]
**Describe The Bug:**
IR devices can not keep the changed names in Home app. The names change back to the assigned names in SwitchBot app + device type every time HB is restarted.

**To Reproduce:**
1. Change name on any of the IR devices in Home app;
2. Restart Homebridge;
3. Check the device name in Home app.

**Expected behavior:**
The device name changed back to the original.

**Logs:**
N/A

**Homebridge Config:**
N/A

**Screenshots:**
<a><img src="https://user-images.githubusercontent.com/48269361/108890290-9fd03c80-75ca-11eb-9b77-de2ca54ca6ed.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/48269361/108890222-89c27c00-75ca-11eb-8f8f-bd09afbd7a75.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/48269361/108890209-83340480-75ca-11eb-8ac3-7023c882c5b4.png" width="250px"></a>

**Device Model:**
Raspberry Pi 3

# **Environment:**

- **Node.js Version**:v14.15.5 
- **NPM Version**: v7.5.4
- **Homebridge Version**: v1.3.1
- **Homebridge SwitchBot Plugin Version**:v3.2.0
- **Homebridge Config UI X Plugin Version**:v4.39.0
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@jonpeng is this only happening with TVs?

**Comment by jonpeng** [comment]
I only have TVs and lights. The lights are OK.

**Comment by donavanbecker** [comment]
so the lights keep their names but TVs don't?

**Comment by jonpeng** [comment]
Yes, correct.

**Comment by donavanbecker** [comment]
this is resolved in `v3.2.2`

**Comment by jonpeng** [comment]
Awesome... All fixed!
