### ISSUE TITLE
After most recent update, IR devices no longer showing up

### ISSUE THREAD

**Issue by erwinloh** [OpenWonderLabs/homebridge-switchbot-openapi#125]
**Describe The Bug:**

I have 3 switch bots, and 2 hub minis (1 running a DIY TV, the other running a Samsung TV) - both IR TV switches were working in the previous plugin version.

I just updated to the most recent version, and for some reason the 3 switch bots are fine but both TV devices are no longer connected. I removed the two TV accessories from the Home app, to see if I can re-add them, but they no longer show up on the list of devices that I can add.

Any advice?

Note that they were working fine in the previous version.

**To Reproduce:**

Update to the most recent plugin version.

**Expected behavior:**

All accessories should be connected and work and if the IR device is removed, I should be able to re-add by choosing to add a new accessory, and choosing one that is not supported by HomeKit, using the code 031-45-154. This no longer is an option.

**Logs:**

24/02/2021, 4:50:44 pm [SwitchBot] {"statusCode":100,"body":{"deviceList":[{"deviceId":"C50EE9528705","deviceName":"Hub Mini Downstairs","deviceType":"Hub Mini","hubDeviceId":"000000000000"},{"deviceId":"C83FBF1DC721","deviceName":"Switch 2","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"C50EE9528705"},{"deviceId":"CBCB0D3101AD","deviceName":"Downstairs Fireplace","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"DC2649445C77"},{"deviceId":"DC2649445C77","deviceName":"Hub Mini Upstairs","deviceType":"Hub Mini","hubDeviceId":"000000000000"},{"deviceId":"FC8F381AD46F","deviceName":"Switch 1","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"C50EE9528705"}],"infraredRemoteList":[{"deviceId":"02-202009220937-95287215","deviceName":"TV","remoteType":"TV","hubDeviceId":"C50EE9528705"},{"deviceId":"02-202101172113-47923768","deviceName":"Upstairs Fireplace","remoteType":"DIY TV","hubDeviceId":"DC2649445C77"}]},"message":"success"}
24/02/2021, 4:50:44 pm [SwitchBot] Total SwitchBot Devices Found: 5
24/02/2021, 4:50:44 pm [SwitchBot] Total IR Devices Found: 2
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"C50EE9528705","deviceName":"Hub Mini Downstairs","deviceType":"Hub Mini","hubDeviceId":"000000000000"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered a Hub Mini
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"C83FBF1DC721","deviceName":"Switch 2","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"C50EE9528705"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered Switch 2 Bot
24/02/2021, 4:50:44 pm [SwitchBot] Restoring existing accessory from cache: Switch 2 Bot DeviceID: C83FBF1DC721
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"CBCB0D3101AD","deviceName":"Downstairs Fireplace","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"DC2649445C77"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered Downstairs Fireplace Bot
24/02/2021, 4:50:44 pm [SwitchBot] Restoring existing accessory from cache: Downstairs Fireplace Bot DeviceID: CBCB0D3101AD
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"DC2649445C77","deviceName":"Hub Mini Upstairs","deviceType":"Hub Mini","hubDeviceId":"000000000000"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered a Hub Mini
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"FC8F381AD46F","deviceName":"Switch 1","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"C50EE9528705"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered Switch 1 Bot
24/02/2021, 4:50:44 pm [SwitchBot] Restoring existing accessory from cache: Switch 1 Bot DeviceID: FC8F381AD46F
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"02-202009220937-95287215","deviceName":"TV","remoteType":"TV","hubDeviceId":"C50EE9528705"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered TV TV
24/02/2021, 4:50:44 pm [SwitchBot] Adding new accessory: TV TV DeviceID: 02-202009220937-95287215
24/02/2021, 4:50:44 pm [SwitchBot] {"deviceId":"02-202101172113-47923768","deviceName":"Upstairs Fireplace","remoteType":"DIY TV","hubDeviceId":"DC2649445C77"}
24/02/2021, 4:50:44 pm [SwitchBot] Discovered Upstairs Fireplace DIY TV
24/02/2021, 4:50:44 pm [SwitchBot] Adding new accessory: Upstairs Fireplace DIY TV DeviceID: 02-202101172113-47923768
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
24/02/2021, 4:50:44 pm at new Bot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/bots.js:58:14)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.createBot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:376:17)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:207:30)
24/02/2021, 4:50:44 pm at processTicksAndRejections (internal/process/task_queues.js:93:5)
24/02/2021, 4:50:44 pm (Use `node --trace-warnings ...` to show where the warning was created)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
24/02/2021, 4:50:44 pm (node:2043) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
24/02/2021, 4:50:44 pm at new Bot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/bots.js:58:14)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.createBot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:376:17)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:207:30)
24/02/2021, 4:50:44 pm at processTicksAndRejections (internal/process/task_queues.js:93:5)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
24/02/2021, 4:50:44 pm at new Bot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/bots.js:58:14)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.createBot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:376:17)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:207:30)
24/02/2021, 4:50:44 pm at processTicksAndRejections (internal/process/task_queues.js:93:5)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
24/02/2021, 4:50:44 pm at new TV (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:57:77)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.createTV (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
24/02/2021, 4:50:44 pm at processTicksAndRejections (internal/process/task_queues.js:93:5)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
24/02/2021, 4:50:44 pm at new TV (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:57:77)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.createTV (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
24/02/2021, 4:50:44 pm at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
24/02/2021, 4:50:44 pm at processTicksAndRejections (internal/process/task_queues.js:93:5)
24/02/2021, 4:50:44 pm (node:2043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
24/02/2021, 4:50:45 pm [SwitchBot] deviceStatus - Upstairs Fireplace "wrong deviceId"
24/02/2021, 4:50:45 pm [SwitchBot] Unable to retreive device status.
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - Downstairs Fireplace {"statusCode":100,"body":{"deviceId":"CBCB0D3101AD","deviceType":"Bot","hubDeviceId":"C50EE9528705","power":"on"},"message":"success"}
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - TV "wrong deviceId"
24/02/2021, 4:50:46 pm [SwitchBot] Unable to retreive device status.
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - Hub Mini Upstairs {"statusCode":100,"body":{},"message":"success"}
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - Switch 2 {"statusCode":100,"body":{"deviceId":"C83FBF1DC721","deviceType":"Bot","hubDeviceId":"C50EE9528705","power":"on"},"message":"success"}
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - Hub Mini Downstairs {"statusCode":100,"body":{},"message":"success"}
24/02/2021, 4:50:46 pm [SwitchBot] deviceStatus - Switch 1 {"statusCode":100,"body":{"deviceId":"FC8F381AD46F","deviceType":"Bot","hubDeviceId":"C50EE9528705","power":"on"},"message":"success"}

**Homebridge Config:**

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYKAF1",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "26:5C:B0:4C:08:DD"
    },
        {
            "platform": "SwitchBot",
            "plugin_map": {
                "plugin_name": "homebridge-switchbot-openapi"
            },
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "openToken": "[SECRET]"
            },
            "options": {
                "bot": {
                    "device_switch": [
                        "CBCB0D3101AD",
                        "C83FBF1DC721",
                        "FC8F381AD46F"
                    ],
                    "device_press": []
                },
                "hide_device": [],
                "meter": {},
                "humidifier": {},
                "curtain": {},
                "fan": {
                    "swing_mode": [],
                    "rotation_speed": []
                },
                "irair": {}
            },
            "devicediscovery": false
        },

# **Environment:**

Bridge Name | HOOBS
HOOBS Version | 3.3.2
Node Version | 14.15.1

**Comment by erwinloh** [comment]
Interesting, I'm getting all these errors in the log, that previously didn't exist, until I upgraded.

What's weird is that when I downgraded to a lower version, the problem still has not resolved.

**Comment by Bgoshua** [comment]
The unhandled promise rejection in your logs points to you're node version being out of date with the current requirements

**Comment by erwinloh** [comment]
Ok, I managed to restore from a previous backup which was running version 3.1.0 of the plugin, and it's all working fine. Thanks for all the feedback, I think I will stop upgrading from now.
