### ISSUE TITLE
Please support "device type: Others" - had to use this type for setting up my extractor hood in my kitchen

### ISSUE THREAD

**Issue by tobiswelten** [OpenWonderLabs/homebridge-switchbot-openapi#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
@tobiswelteni I could potentially do that but what do you want it to display as?

**Comment by tobiswelten** [comment]
Hey,


That is great.
I trained the hub to turn on/off my extractor hood in the hood via infrared signals.
I think, in Homekit the closes you can get in terms of supported device types are „Fans“ - does that answer your questions?

**Comment by donavanbecker** [comment]
@tobiswelten yes it does. So you just need on and off?

**Comment by tobiswelten** [comment]
This is the main task, I also trained the hub to increase and decrease the fan speed but that is more P2.

**Comment by donavanbecker** [comment]
can you take a screenshot of how it is setup in the switchbot app?

**Comment by donavanbecker** [comment]
@tobiswelten have you tried just setting it up under fans? and just doing a Custom Fan? you should be able to do that in the SwitchBot App.
