### ISSUE TITLE
Curtain Stopped Working

### ISSUE THREAD

**Issue by jbk1988** [OpenWonderLabs/homebridge-switchbot-openapi#138]
Hi,

Since the last three updates, my curtains have stopped working in HomeKit entirely. They worked perfectly before. 

**To Reproduce:**

I tried to uninstall and reinstall the plugin. 

**Expected behavior:**

I hoped that this would fix it, it did not. 

**Logs:**

2/25/2021, 1:16:11 PM [SwitchBot] Restoring existing accessory from cache: Living Room Left Curtain Curtain DeviceID:
2/25/2021, 1:16:11 PM [SwitchBot] Restoring existing accessory from cache: Living Room Right Curtain Curtain DeviceID:
2/25/2021, 1:16:11 PM (node:527) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onGet is not a function
2/25/2021, 1:16:11 PM at new Curtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:54:14)
2/25/2021, 1:16:11 PM at SwitchBotPlatform.createCurtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:475:17)
2/25/2021, 1:16:11 PM at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:217:30)
2/25/2021, 1:16:11 PM at processTicksAndRejections (internal/process/task_queues.js:97:5)
2/25/2021, 1:16:11 PM (node:527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2/25/2021, 1:16:11 PM (node:527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2/25/2021, 1:16:11 PM (node:527) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onGet is not a function
2/25/2021, 1:16:11 PM at new Curtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:54:14)
2/25/2021, 1:16:11 PM at SwitchBotPlatform.createCurtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:475:17)
2/25/2021, 1:16:11 PM at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:217:30)
2/25/2021, 1:16:11 PM at processTicksAndRejections (internal/process/task_queues.js:97:5)
2/25/2021, 1:16:11 PM (node:527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

 {
            "platform": "SwitchBot",
            "plugin_map": {
                "plugin_name": "homebridge-switchbot-openapi"
            },
            "name": "SwitchBot",
            "credentials": {
                "notice": "Keep your token a secret!",
                "openToken": "XXX"
            },
            "options": {}
        }

**Comment by donavanbecker** [comment]
@jbk1988, You need to have homebridge v1.3.1 installed as the changelogs says.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
