### ISSUE TITLE
Change the project name

### ISSUE THREAD

**Issue by SwitchBot-Wonderlabs** [OpenWonderLabs/homebridge-switchbot-openapi#14]
Hi, @donavanbecker , 
I'm sorry we could not spend a lot of time in the open source community.
And I'm glad you started developing this plugin, thank you for your time.
Can you change the project name to something like homebridge-switchbot-xxx?
Also, can you join [OpenWonderLabs ](https://github.com/OpenWonderLabs) and move the project to that organization?

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs That works for me to move it to your organization.

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs do you want me to keep the name?

**Comment by SwitchBot-Wonderlabs** [comment]
> @SwitchBot-Wonderlabs do you want me to keep the name?

Maybe change to homebridge-switchbot-openapi.
I invite you to join the SwitchBot organization on [NPM](https://www.npmjs.com/).

**Comment by donavanbecker** [comment]
do you want that changed for both npm and GitHub? if you want github changed, you will have to do it now since I don't have security. if you just want npm let me know.

**Comment by SwitchBot-Wonderlabs** [comment]
> do you want that changed for both npm and GitHub? if you want github changed, you will have to do it now since I don't have security. if you just want npm let me know.

I change the project name in github.
Please change the name in npm.

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs I have unpunished on npm and I am now re publishing under homebridge-switchbot-openapi. Once published, I will moved to organization on npm.

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs all done! is there a better way for us to communicate than issues?

**Comment by SwitchBot-Wonderlabs** [comment]
> @SwitchBot-Wonderlabs all done! is there a better way for us to communicate than issues?

Either way, it's up to you.

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs the homebridge discord server is probably easiest. if that works? same username on there.

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs I am excited to get this project going. but still need to get the open token first. not even sure if what I have will work.

**Comment by SwitchBot-Wonderlabs** [comment]
> @SwitchBot-Wonderlabs I am excited to get this project going. but still need to get the open token first. not even sure if what I have will work.
What's your SwitchBot account's username?

**Comment by donavanbecker** [comment]
donavan.becker@icloud.com

I believe.
