### ISSUE TITLE
IR Features ported to HOOBS please

### ISSUE THREAD

**Issue by peterfrying** [OpenWonderLabs/homebridge-switchbot-openapi#140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by peterfrying** [comment]
Thank you very much for supporting HOOBS. I no longer need to use IFTTT and save hundreds of dollars over my life time. As a thank you, I will purchase more of your products for my family. 

I would like to kindly ask if you can put IR blaster feature through HomeKit, even if it is a press only button, it is the one feature that I will need before I can lose IFTTT altogether. 

Many thanks for all that you do

**Comment by donavanbecker** [comment]
@peterfrying, You need to have homebridge v1.3.1.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
