### ISSUE TITLE
Add Switchbot plug

### ISSUE THREAD

**Issue by takoyaki860** [OpenWonderLabs/homebridge-switchbot-openapi#141]
**Is your feature request related to a problem? Please describe.**

I want to use  Switchbot Plug with Homebridge

**Describe the solution you'd like**

Adapt Switchbot Plug to Homebridge

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
@takoyaki860 Did the plugin n@ work for you?

**Comment by takoyaki860** [comment]
Switchbot plug is displayed in the log as " "deviceType": "plug" " and "message" is "success", but it isn't  displayed in Home App on iPhone.

**Comment by donavanbecker** [comment]
> @donavanbecker Switchbot plug is displayed in the log as " "deviceType": "plug" " and "message" is "success", but it isn't  displayed in Home App on iPhone.

Okay. I don't have one so can't test it, but I will add what I think will work and then can you test a beta version?

**Comment by takoyaki860** [comment]
> Okay. I don't have one so can't test it, but I will add what I think will work and then can you test a beta version?

Thanks! Where can I get that beta version?

**Comment by donavanbecker** [comment]
@takoyaki860 I haven't released it yet. Once I do I will give you instructions. are you using Homebridge UI?

**Comment by takoyaki860** [comment]
Yes

**Comment by donavanbecker** [comment]
okay new beta is out: I have a log that says `PLEASE POST THIS BACK INTO ISSUE TO GET INFO!` I need that info for the plug to update HomeKit with the correct info. Let me know if the plugin finds the plug now though?

Beta: `3.3.5-beta.0`

**Comment by takoyaki860** [comment]
Here is that

`PLEASE POST THIS BACK INTO ISSUE TO GET INFO! {"statusCode":100,"body":{"deviceId":"E0980683AA58","deviceType":"Plug","hubDeviceId":"E0980683AA58","power":"off"},"message":"success"}`

**Comment by donavanbecker** [comment]
@takoyaki860 okay I just pushed out the finishing touches for the plug. can you give it another try with the new beta, make sure it updates correctly in the home app and try it out for a little and report back if all is well I will release a new version.

Beta: `3.3.5-beta.1`

**Comment by takoyaki860** [comment]
It's working properly! 

Log says ` Sending request for <name> Plug to SwitchBot API. command: turnOn parameter: default commandType: command`.

**Comment by donavanbecker** [comment]
@takoyaki860 Awesome! I will release an update today then! Thanks for Testing!
