### ISSUE TITLE
Device doesn't appear in Home app

### ISSUE THREAD

**Issue by spadrille2** [OpenWonderLabs/homebridge-switchbot-openapi#145]
**Describe The Bug:**

I have a TV controled by IR with the Switchbot Hub Mini. The device is shown in Homebridge but not in the Home app. I don't know if that could be the problem but i see in the switchbot plugin settings that there is a device ID in the "Hide device" setting. If i remove it, save and open the setting again, the ID is still in the hidden devices.

**To Reproduce:**

 Always happen even after reboot of Homebridge.

**Expected behavior:**

 I was expecting to see the device appears in the Home app.

**Logs:**

```
[02/03/2021 à 18:35:49] [spadrille@me.com] Initializing SwitchBot platform...
[02/03/2021 à 18:35:49] [spadrille@me.com] Using Default Refresh Rate.
[02/03/2021 à 18:35:49] [spadrille@me.com] Using Default Push Rate.
[02/03/2021 à 18:35:50] [spadrille@me.com] {"statusCode":100,"body":{"deviceList":[{"deviceId":"FD7A25B9DFCE","deviceName":"Hub Mini","deviceType":"Hub Mini","hubDeviceId":"000000000000"}],"infraredRemoteList":[{"deviceId":"02-202103021441-44998279","deviceName":"Television","remoteType":"TV","hubDeviceId":"FD7A25B9DFCE"}]},"message":"success"}
[02/03/2021 à 18:35:50] [spadrille@me.com] Total SwitchBot Devices Found: 1
[02/03/2021 à 18:35:50] [spadrille@me.com] Total IR Devices Found: 1
[02/03/2021 à 18:35:50] [spadrille@me.com] {"deviceId":"FD7A25B9DFCE","deviceName":"Hub Mini","deviceType":"Hub Mini","hubDeviceId":"000000000000"}
[02/03/2021 à 18:35:50] [spadrille@me.com] Discovered a Hub Mini
[02/03/2021 à 18:35:50] [spadrille@me.com] {"deviceId":"02-202103021441-44998279","deviceName":"Television","remoteType":"TV","hubDeviceId":"FD7A25B9DFCE"}
[02/03/2021 à 18:35:50] [spadrille@me.com] Discovered Television TV
[02/03/2021 à 18:35:50] [spadrille@me.com] Adding new accessory: Television TV DeviceID: 02-202103021441-44998279
Preparing Advertiser for 'Television TV F648' using ciao backend!
[02/03/2021 à 18:35:51] [spadrille@me.com] deviceStatus - Hub Mini {"statusCode":100,"body":{},"message":"success"}
[02/03/2021 à 18:35:51] [spadrille@me.com] deviceStatus - Television "wrong deviceId"
[02/03/2021 à 18:35:51] [spadrille@me.com] Unable to retreive device status.
```

**Homebridge Config:**

```json
{
            "name": "spadrille@me.com",
            "credentials": {
                "openToken": "XXXXXXXXXXXXX",
                "notice": "Keep your token a secret!"
            },
            "devicediscovery": true,
            "platform": "SwitchBot"
        }
```

**Screenshots:**

**Device Model:**
Hub Mini

# **Environment:**

- **Node.js Version**: 14.16.0
- **NPM Version**: 6.14.11
- **Homebridge Version**: 1.3.1
- **Homebridge SwitchBot Plugin Version**:3.3.4
- **Homebridge Config UI X Plugin Version**:4.39.1
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@spadrille2 TVs are extern devices did you try adding the tv like you did homebridge when you first setup homebridge?

**Comment by spadrille2** [comment]
4m not sur i understand your question. I had Homebridge already with other devices. I added the the Switchbot plugin to control the TV with IR.

**Comment by spadrille2** [comment]
Do you mean that i should have been adding the TV to the Home app the same way i have added Homebridge to the Home app? Should i have scanned a QR code just for the TV? Where was i suppose to find this separate QR code? I'm sorry, i'm really not sure about what you mean?

**Comment by donavanbecker** [comment]
its the same QR code that you used to scan homebridge and yes you add it the same way as you added it to homebridge.

**Comment by spadrille2** [comment]
If i scan with the Home app the QR code that is shown in Homebridge, the Home app tell me that i have already add this accessory, which is Homebridge. I don't understand. How the same QR code could be both the Homebridge and a TV? I think we don't understand each other.

**Comment by donavanbecker** [comment]
@spadrille2 no I understand you. Click `I Don't Have a Code or Cannot Scan` then you will see your tv, click it, and then click scan with camera (or something like that.)

**Comment by spadrille2** [comment]
OK. I have tried that. After i have clicked on "i have no code", it show me two different Homebridges ( i didn't knew it could be possible). Then i choose one of the Homebridges and i select "use photo" but i have an error "Impossible to add accessory". I have tried on both Homebridges.

**Comment by spadrille2** [comment]
Maybe i should have mention that before having the problem of the accessory not showing up in the Home app, i had managed to have it show up in a previous try. I just added the plugin to the bridge and the accessory showed up in the Home app without any new QR code scanning. But the problem is that in the Home App, there was an error message saying that this accessory couldn't be used in Home. I don't why it showed up if it could'nt be used... Anyway, i decided to delete the plugin and install it again. THEN i had the problem of the device not showing up in Home. I hope this could help.

**Comment by spadrille2** [comment]
Is there anything i should change in the default settings in `IR Device Settings`?
Is that normal that i have a device ID in the `Hidden Devices` settings?

**Comment by donavanbecker** [comment]
not on reinstall, if it is `02-202103021441-44998279` delete it.

**Comment by donavanbecker** [comment]
you may also have to reset the pairing of the TV, are you using Homebridge UI?

**Comment by spadrille2** [comment]
The ID in the Hidden device is 81F3UT59513F (so, not 02-202103021441-44998279). Anyway, it seems that i can't delete it. It reappears after saving.
Yes i am using Homebridge UI. 
When you tell me to reset the pairing of the TV, do you you mean the pairing inside the Switchbot app? Because i already tried to delete the devices inside the Switchbot app and even create a new Switchbot account. That didn't helped.

**Comment by donavanbecker** [comment]
@spadrille2 I don't know why you would try all that but that could potentially mess a lot up.

there is a setting in Homebridge UI, here you should see your tv and should be able to reset the pair and then re add like I mentioned above.
<img width="221" alt="Screen Shot 2021-03-02 at 4 32 20 PM" src="https://user-images.githubusercontent.com/9875439/109724219-de3e9c00-7b74-11eb-8193-555707341027.png">
<img width="1353" alt="Screen Shot 2021-03-02 at 4 32 35 PM" src="https://user-images.githubusercontent.com/9875439/109724254-ee567b80-7b74-11eb-9583-2a21012f58da.png">

**Comment by spadrille2** [comment]
I realize that i still have a lot to learn about Homebridge (i'm a newbie). I had a lot of my "old devices" from my previous tests in the list of external accessories. I have deleted everything except Homebridge and restarted. Now i just have Homebridge and my TV listed. But nothing new appears in the Home app. Do i need to try to add the TV in the Home app with the QR code as you suggested earlier?

**Comment by donavanbecker** [comment]
yes but you will have to click the I don't have a code

**Comment by spadrille2** [comment]
I have selected "i dont have a code", then i have choosen one of the 2 Homebridges instances, then i have entered the code that is in the status page, under the QR code. It gives me an error message saying that my code is incorrect, same if i scan the QR code.

**Comment by donavanbecker** [comment]
It's not going to show up as a homebridge instance, it will show up as a TV.

**Comment by donavanbecker** [comment]
turn devicediscovery off, that is only needed for new devices....

**Comment by spadrille2** [comment]
It doesn't. Here is what i see. (sorry, it's in french)
![IMG_25E982474380-1](https://user-images.githubusercontent.com/63778769/109728291-2f22b480-7bb6-11eb-8aed-a738a9cf3b88.jpeg)

**Comment by spadrille2** [comment]
Device discovery is already off.

**Comment by spadrille2** [comment]
Another thing I should have mentionned. Right now I’m not near the Switchbot hub. I’m in a remote place making adjustments to Homebridge thru VNC. When I tried to scan a the QR code it is with my iPhone that have authorization to add accessory to my HomeKit setup. But I’m not physically near this installations. Does it have any consequence in the TV not showing up as an accessory when I try to pair it with « I have no code »?

**Comment by donavanbecker** [comment]
Yes! Wait till you get to your location...

**Comment by spadrille2** [comment]
Yes ! That was it ! It works now. Thank a lot for your help. 
Maybe just a last question. The power button on my TV remote is a toggle ON-OFF. So, sometimes, the TV is on but Home think its off, or the opposite. Is there anyway to make Home know what is the real state of the  TV?

**Comment by donavanbecker** [comment]
@spadrille2 Since it is IR and IR is only a 1 way signal. No there isn't. If there was I would definitely implement it.

**Comment by lakmuse** [comment]
Hi, I can't seem to find my curtains either. 

The setup seems OK otherwise (they appear in Homebridge and they work if controlled from there), but I just can't make the curtains appear when I try adding them in Home app. I'm right next to the Mini hub and scanning devices in the list.

Also tried rebooting Homebridge + removing Cached accessories in Homebridge settings. I also tried rebooting iPhone & killing the Home app. Any other ideas?

**Comment by lakmuse** [comment]
> Hi, I can't seem to find my curtains either.
> 
> The setup seems OK otherwise (they appear in Homebridge and they work if controlled from there), but I just can't make the curtains appear when I try adding them in Home app. I'm right next to the Mini hub and scanning devices in the list.
> 
> Also tried rebooting Homebridge + removing Cached accessories in Homebridge settings. I also tried rebooting iPhone & killing the Home app. Any other ideas?

OK solved it myself. Deleted all content from accessories & persist folders, and set Switchbot up with a separate bridge after renaming it. Now all devices appeared!
