### ISSUE TITLE
Errors with Homebridge 1.3.2

### ISSUE THREAD

**Issue by SimonLawson70** [OpenWonderLabs/homebridge-switchbot-openapi#147]
**Describe The Bug:**

Since the Homebridge 1.3.2 update, I’m seeing error 500 showing in the logs, and also a failure to get the curtain state.

This error is only happening with the Curtain pair, my ‘Bot seems to be fine.

I have tried deleting the cached accessory and restarting Homebridge but the error comes back. The curtains still show up in the Home app but the state doesn’t seem to be updating reliably.

**To Reproduce:**

Install Homebridge 1.3.2 with a (pair) of SwitchBot curtain.

**Expected behavior:**

No error (like it was in HB 1.3.0)

**Logs:**

This error is now showing up in the logs

`[3/4/2021, 11:40:42 AM] [SwitchBot] Curtain - Failed to refresh status of Front Bedroom Curtains "Request failed with status code 500" undefined`

And also

```
[3/4/2021, 6:35:43 PM] [SwitchBot] Curtain - Failed to refresh status of Front Bedroom Curtains "getaddrinfo EAI_AGAIN api.switch-bot.com” undefined
[3/4/2021, 6:38:13 PM] [SwitchBot] Curtain - Failed to refresh status of Front Bedroom Curtains "getaddrinfo EAI_AGAIN api.switch-bot.com” undefined
```

**Homebridge Config:**
```

{
            "name": "SwitchBot",
            "credentials": {
                "openToken": “It’s a secret!",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 150,
                "bot": {
                    "device_switch": [
                        "F53BC95303D9"
                    ],
                    "switch": true
                },
                "meter": {
                    "unit": 0
                }
            },
            "platform": "SwitchBot"
        },

```
**Screenshots:**

**Device Model:**

Switcbot Curtain (a left and right pair)
# **Environment:**

- **Node.js Version**: 14.16.0
- **NPM Version**: 6.14.11
- **Homebridge Version**: 1.3.2
- **Homebridge SwitchBot Plugin Version**: 3.4.0
- **Homebridge Config UI X Plugin Version**: 4.39.1
- **Operating System**: Docker on Synology NAS

**Comment by donavanbecker** [comment]
@SimonLawson70 [SwitchBotAPI standard-http-error-codes](https://github.com/OpenWonderLabs/SwitchBotAPI#standard-http-error-codes)

**Comment by donavanbecker** [comment]
v3.4.1 released
