### ISSUE TITLE
Bug with DIY TV - Volume changing doesn‘t work

### ISSUE THREAD

**Issue by Kohle81** [OpenWonderLabs/homebridge-switchbot-openapi#156]
**Describe The Bug:**
Since I habe updated homebridge to version 1.3.2 the DIY TV can switch on, but when I want to change volume, the TV is going out.....

I am on plugin version 3.4.0

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**
![094A88D7-9304-4C7F-9019-9CCBFFA2C7F1](https://user-images.githubusercontent.com/33038709/110390327-1dce2200-8066-11eb-9f09-f439790faa16.png)

**Device Model:**

# **Environment:**

- **Node.js Version**: <14.16.0>
- **NPM Version**: <6.14.11>
- **Homebridge Version**: <1.3.2>
- **Homebridge SwitchBot Plugin Version**:3.4.0
- **Homebridge Config UI X Plugin Version**: 4.39.1
- **Operating System**:

**Comment by donavanbecker** [comment]
@Kohle81 what do you mean by going out?

**Comment by Kohle81** [comment]
When the diy TV is activated and I try to increase the volume via the apple remote (see picture above), the Switchbot Hub also sends an IR signal to switch off the TV.  However, the DIY TV is still shown as activated in Homekit.
