### ISSUE TITLE
Switchbot Curtain parameters for Shortcuts

### ISSUE THREAD

**Issue by beatpaul** [OpenWonderLabs/homebridge-switchbot-openapi#161]
**Is your feature request related to a problem? Please describe.**

 Hi!
I would really like to use the switchbot Curtains with Shortcuts commands.
e.g. i would like to program my wall switch that if a button is pressed:
`if curtain is open --> close it --> else --> open it`

The problem is, there are no useful parameters available in the shortcuts app

**Describe the solution you'd like**

Could these parameters be made alvailable ?

**Comment by beatpaul** [comment]
@donavanbecker 

Hi! Could you reopen / take a look at this issue please

Here is a screenshot using Shortcuts
![IMG_2678](https://user-images.githubusercontent.com/33185643/111069186-39a15000-84cc-11eb-902f-85ed459f81b4.png)

No options are available:

![IMG_2679](https://user-images.githubusercontent.com/33185643/111069197-402fc780-84cc-11eb-9efb-fb7578366f0f.png)

thx for this great plugin

**Comment by donavanbecker** [comment]
@beatpaul I guess I'm not sure if that's something in my control to add. Also if issue templates are used and nothing is erased this issue would have stayed open.
