### ISSUE TITLE
Curtain always moves in silent mode even when set to performance mode

### ISSUE THREAD

**Issue by ucfhall** [OpenWonderLabs/homebridge-switchbot-openapi#164]
**Describe The Bug:**
When closing a curtain using the plugin, either via Alexa or HomeKit, the curtain moves at silent mode even when set to performance mode in the Switchbot app. 

**To Reproduce:**
Add curtain to Switchbot app and set to Performance Mode. Add to Homebridge. Attempt to open or close curtain.

**Expected behavior:**
Curtain moves at silent mode even when set to performance mode in the Switchbot app. 

**Logs:**
[3/18/2021, 3:34:33 PM] [SwitchBot] Sending request for Bedroom Curtain to SwitchBot API. command: setPosition parameter: 0,ff,100 commandType: command
[3/18/2021, 3:34:36 PM] [SwitchBot] Checking Bedroom Curtain Status ...
[3/18/2021, 3:34:41 PM] [SwitchBot] Checking Bedroom Curtain Status ...
```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "[REMOVED]",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        },
```

**Screenshots:**
NA

**Environment:** ?

* **Node.js Version**: 14.16.0
* **NPM Version**: 7.6.3
* **Homebridge Version**: 1.3.4
* **Homebridge SwitchBot Plugin Version**: 3.4.1
* **Homebridge Config UI X Version**: 4.40.0
* **Operating System**: Ubuntu Server 20.04
* **Process Supervisor**: hb-service

**Comment by ucfhall** [comment]
I saw that…I didn’t say it wasn’t sending the command, I’m saying that regardless the output is not expected. The curtain doesn’t move at that speed.

**Comment by donavanbecker** [comment]
@ucfhall i don't feel like it's a plugin issue then
