### ISSUE TITLE
multi switches shown in homekit 

### ISSUE THREAD

**Issue by dickman138** [OpenWonderLabs/homebridge-switchbot-openapi#165]
Hi, 
I only got ONE press bot but homekit shown totally 3 switches on the home app. 

I can control the bot with one of them but the other two are not working.

I have deleted the switch bot at the advanced setting but same not success.  An bot id not belong to me shown and i cannot deleted it.

I only add my press bot id successfully at the advanced setting.

Need your help to remove the excess switches on the Home app.

Thanks

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
I am going to close this issue since you haven't filled out all the fields for me to be able to troubleshoot your issues.
