### ISSUE TITLE
Curtain Shows Works, Bots Show Up in HK But Don't Work

### ISSUE THREAD

**Issue by joecan00** [OpenWonderLabs/homebridge-switchbot-openapi#169]
Not a bug, just need help.

This is likely because I'm doing something wrong, but I can't seem to get my Bots to work in HomeKit. Both Curtains show up and work but the button bots just show up but don't work in HomeKit or the HomeBridge UI.

What am I supposed to be using as the DeviceID? Is it just the name I've give the bot?

**Comment by joecan00** [comment]
It's a question. What is the DeviceID... what's the answer?

**Comment by donavanbecker** [comment]
@joecan00 Follow issue template in the future.

DeviceID is in logs
