### ISSUE TITLE
Hide Humidifier Humidity Sensor

### ISSUE THREAD

**Issue by ronniemies** [OpenWonderLabs/homebridge-switchbot-openapi#179]
**Is your feature request related to a problem? Please describe.**

I am unable to remove the humidity sensor from the accessory, only temperature is removable. 

**Describe the solution you'd like**

A Hide Humidifier's Humidity Sensor Option

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by donavanbecker** [comment]
I am going to close this. If this is still happening open new issue under bug template and fill in all info so that I can better understand your situation.
