### ISSUE TITLE
SwitchBot Curtain Beta Causing 401 Error

### ISSUE THREAD

**Issue by matclothier** [OpenWonderLabs/homebridge-switchbot-openapi#20]
Since installing the new beta I get a 401 error. 

Install the latest beta

You get a 401 error

```

[12/28/2020, 10:09:27 PM] Homebridge v1.2.5 is running on port 53257.
[12/28/2020, 10:09:27 PM] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
@matclothier, if you try installing older versions are you getting this error?

**Comment by matclothier** [comment]
It works fine with 1.01 apart from the closing issue but not 1.02 beta.

**Comment by SwitchBot-Wonderlabs** [comment]
Error 401 is caused by too many requests from v1.0.2 beta.3.

**Comment by SwitchBot-Wonderlabs** [comment]
@matclothier try v1.0.2-beta.8.

**Comment by matclothier** [comment]
That worked. All working perfectly now. Great job thanks

**Comment by paintthenet** [comment]
i have this issue in v1.0.2-beta.10

[30/12/2020, 20:34:41] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"

and one Curtain is not available in the Device List . The other works fine.

There is also one ID in the Hide Device Settings and I cannot delete the id.


OS | Raspbian GNU/Linux Buster (10)
Node.js Version | v14.15.3
Npm v6.14.9
Homebridge  v1.1.7
Plugin v1.0.2-beta.10

**Comment by donavanbecker** [comment]
> i have this issue in v1.0.2-beta.10
> 
> 
> 
> [30/12/2020, 20:34:41] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
> 
> 
> 
> and one Curtain is not available in the Device List . The other works fine.
> 
> 
> 
> There is also one ID in the Hide Device Settings and I cannot delete the id.
> 
> 
> 
> 
> 
> OS | Raspbian GNU/Linux Buster (10)
> 
> Node.js Version | v14.15.3
> 
> Npm v6.14.9
> 
> Homebridge  v1.1.7
> 
> Plugin v1.0.2-beta.10
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Can you open a separate issue with your specific setup info?

**Comment by SwitchBot-Wonderlabs** [comment]
> i have this issue in v1.0.2-beta.10
> 
> [30/12/2020, 20:34:41] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
> 
> and one Curtain is not available in the Device List . The other works fine.
> 
> There is also one ID in the Hide Device Settings and I cannot delete the id.
> 
> OS | Raspbian GNU/Linux Buster (10)
> Node.js Version | v14.15.3
> Npm v6.14.9
> Homebridge v1.1.7
> Plugin v1.0.2-beta.10

@paintthenet Do you have a lot of devices?  You can try increasing the TTL.

> [SwitchBotAPI#request-limit](https://github.com/OpenWonderLabs/SwitchBotAPI#request-limit)
> The amount of API calls per day is limited to 1000 times. Going over that limit will return "Unauthorized."
