### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by jahnkenneth** [OpenWonderLabs/homebridge-switchbot-openapi#21]
**Describe The Bug:**

The plugin has been working prefect for the last few days, but today I get this error:

[31/12/2020, 12:27:42] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"

I have 4 bots

**To Reproduce:**

Start HomeBridge

**Expected behavior:**
Not getting error 401

**Logs:**

[31/12/2020, 12:27:42] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
{
  "name": "SwitchBot",
  "credentials": {
    "openToken": "xxxxxxxxxxx",
    "notice": "Keep your token a secret!"
  },
  "options": {
    "hide_device": [
      "D29AAC6DDF90"
    ]
  },
  "platform": "SwitchBot"
}
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 14.15.3
- **NPM Version**: v6.14.9
- **Homebridge Version**: 1.1.7
- **Homebridge SwitchBot Plugin Version**: 1.0.2 beta 11
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
@jahnkenneth You will need to post your config

**Comment by jahnkenneth** [comment]
{
    "bridge": {
        "name": "Homebridge 3E15",
        "username": "0E:CB:5A:E7:3E:15",
        "port": 51552,
        "pin": "560-32-611"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": «xxxxxxxxxxx»,
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "D29AAC6DDF90"
                ]
            },
            "platform": "SwitchBot"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxx",
                "password": "Xxxxxxx",
                "countryCode": "47",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ]
}

**Comment by donavanbecker** [comment]
@jahnkenneth can you try setting your TTL to 300? and then see if it works itself out. We are changing that as default going forward with the next release.

**Comment by jahnkenneth** [comment]
Will try. When wil I be «unblocked» (assuming that was the case..)?

Med hilsen,
Jahn Kenneth Juliussen

**Comment by donavanbecker** [comment]
> Will try. When wil I be «unblocked» (assuming that was the case..)? Med hilsen, Jahn Kenneth Juliussen
> […](#)

@jahnkenneth, I am not sure. I have only had this happen once. It was resolved that day. so at least by tomorrow.

**Comment by jahnkenneth** [comment]
Sikring now! 👍🏻
