### ISSUE TITLE
The position of the curtain is shifted by 1%.

### ISSUE THREAD

**Issue by pc2000-10** [OpenWonderLabs/homebridge-switchbot-openapi#236]
**Describe The Bug:**
When I close the curtains in the Home app, they become "closed", but after a while, the Home app shows "1% open"; the SwitchBot app side is fine, and I checked the logs, but could not find any curtain movement logs.

**To Reproduce:**

Keep the curtain closed with Home app.
Wait for a certain amount of time.

**Expected behavior:**
Curtains in the Home app will show "1% open".

**Logs:**
None.

**Homebridge Config:**

```json
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "None",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                ]
            },
            "platform": "SwitchBot"
        }
```

**Screenshots:**
![2021-07-22 18 33 26 (2)](https://user-images.githubusercontent.com/77045890/126618796-aca2d481-365a-4188-8c18-10cc80f7dbf3.png)

**Device Model:**
iPhone 7
Raspberry Pi 4 Model B

# **Environment:**

- **Node.js Version**: v14.17.2
- **NPM Version**: v6.14.13
- **Homebridge Version**: v1.3.4
- **Homebridge SwitchBot Plugin Version**: v3.4.3
- **Homebridge Config UI X Plugin Version**: v4.41.1
- **Operating System**: Raspbian

**Comment by Dakvar** [comment]
I have the exact same issue and it's driving me nuts!

**Comment by andrewsfchoi** [comment]
Same here, same exact issue.

**Comment by donavanbecker** [comment]
There is an option in the config to set the min and max, this will tell the plugin what the min and Mac are. Since these are the numbers the API send back, there isn't anything else I can do to fix this.
<a><img src="https://user-images.githubusercontent.com/9875439/129189863-d5e7a41d-f560-470d-839b-95e752dcc9fe.jpeg" width="250px"></a>
