### ISSUE TITLE
SwitchBot Bot Beta Causes Homebridge Crash

### ISSUE THREAD

**Issue by MikeDeltaHH** [OpenWonderLabs/homebridge-switchbot-openapi#29]
After updating the plugin to the 1.1.1 beta 4 my homebridge crashed

Update 1.1.0 to 1.1.1 beta 4

**Homebridge Config:**

my config.json:

[config.json.txt](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/files/5798076/config.json.txt)

Logs:

[homebridge.log.txt](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/files/5798049/homebridge.log.txt)

**Device Model:**

ESX virtual machine

# **Environment:**

- **Node.js Version**: v14.15.4 
- **NPM Version**: v6.14.11
- **Homebridge Version**: v1.2.5
- **Homebridge SwitchBot Plugin Version**: 1.1.1 beta4
- **Homebridge Config UI X Plugin Version**: v4.36.0 
- **Operating System**: Ubuntu Linux 20.04 LTS

**Comment by donavanbecker** [comment]
@MikeDeltaHH from what I can tell your config:
```
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxx",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
```
doesn't have the bot settings configured. you must set those in the plugin settings. let me know if that doesn't help or you need help finding those settings.

**Comment by MikeDeltaHH** [comment]
gnaaaaa... my fault!
