### ISSUE TITLE
Switchbot Hub Mini IR TV Support

### ISSUE THREAD

**Issue by pulkitjalan** [OpenWonderLabs/homebridge-switchbot-openapi#40]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Support for TV via IR on Hub mini.

**Describe alternatives you've considered**

Displayed as TV in Homekit

**Additional context**

```json
{
   "statusCode":100,
   "body":{
      "deviceList":[
         {
            "deviceId":"A123B45B6C78",
            "deviceName":"Hub",
            "deviceType":"Hub Mini",
            "hubDeviceId":"000000000000"
         }
      ],
      "infraredRemoteList":[
         {
            "deviceId":"12-1234567891011-12131415",
            "deviceName":"Bedroom TV",
            "remoteType":"TV",
            "hubDeviceId":"A123B45B6C78"
         }
      ]
   },
   "message":"success"
}
```

**Comment by donavanbecker** [comment]
@pulkitjalan, I will work on implementing this. Might take a little since I haven't implemented a TV before and with IR devices only being a 1 way thing, will also make it a little more fun.

Once I get a good working product. can you beta test it for me?

**Comment by pulkitjalan** [comment]
Sure, happy to test it out. Thanks for the great work!

--
Pulkit Jalan
pulkit1990@gmail.com

**Comment by whatUwant** [comment]
I started a few days ago with speaker remote but the accessory is not recognized as speaker in the Home app. 
Oddly the very same accessory is correctly recognized by [Controller](https://apps.apple.com/us/app/controller-for-homekit/id1198176727).

<img src="https://user-images.githubusercontent.com/2762992/104499612-07679500-55e6-11eb-87c0-862cbce158ca.JPG" width="50%" /><img src="https://user-images.githubusercontent.com/2762992/104499604-059dd180-55e6-11eb-94b4-ce67c43989dc.JPG" width="50%" />

**Comment by donavanbecker** [comment]
@pulkitjalan, work in progress!! I have the tv being found by the plugin and registering as an external TV. If you would like to try it out? you can, you won't be able to do anything with it yet, but it will display the TV.

This will display the TV as an extern accessory, so you will have to click the `+` to add accessories and then you will see your TV. 

If you try it let me know, and also let me know if you have any issues.

**Comment by donavanbecker** [comment]
> I started a few days ago with speaker remote but the accessory is not recognized as speaker in the Home app.

nice, PRs are always welcome!!!

**Comment by pulkitjalan** [comment]
Awesome @donavanbecker, yup exactly as you said. Added it manually into the Home app, enter the code and it shows up.

<img width="496" alt="switchbot_tv" src="https://user-images.githubusercontent.com/4124930/104514635-7abed600-55e9-11eb-8102-8774382b4e4c.png">

I also have these 2 showing in Homebridge, is that expected?

<img width="358" alt="Screenshot 2021-01-13 at 21 56 18" src="https://user-images.githubusercontent.com/4124930/104515120-43045e00-55ea-11eb-976c-54c99734d601.png">

Including the logs incase they are of any help.

```
[1/13/2021, 9:43:10 PM] [SwitchBot] {"statusCode":100,"body":{"deviceList":[{"deviceId":"A123B45B6C78","deviceName":"Hub","deviceType":"Hub Mini","hubDeviceId":"000000000000"}],"infraredRemoteList":[{"deviceId":"12-1234567891011-12131415","deviceName":"Bedroom TV","remoteType":"TV","hubDeviceId":"A123B45B6C78"}]},"message":"success"}
[1/13/2021, 9:43:10 PM] [SwitchBot] Total Devices Found: 1
[1/13/2021, 9:43:10 PM] [SwitchBot] {"deviceId":"A123B45B6C78","deviceName":"Hub","deviceType":"Hub Mini","hubDeviceId":"000000000000"}
[1/13/2021, 9:43:10 PM] [SwitchBot] Discovered a Hub Mini
[1/13/2021, 9:43:10 PM] [SwitchBot] {"deviceId":"12-1234567891011-12131415","deviceName":"Bedroom TV","remoteType":"TV","hubDeviceId":"A123B45B6C78"}
[1/13/2021, 9:43:10 PM] [SwitchBot] Discovered Bedroom TV TV
[1/13/2021, 9:43:10 PM] [SwitchBot] Adding new accessory: Bedroom TV TV DeviceID: 12-1234567891011-12131415
[1/13/2021, 9:43:10 PM] Bedroom TV TV 0ABC is running on port 40235.
[1/13/2021, 9:43:10 PM] Please add [Bedroom TV TV 0ABC] manually in Home app. Setup Code: 000-00-000
[1/13/2021, 9:43:11 PM] [SwitchBot] deviceStatus - Bedroom TV "wrong deviceId"
[1/13/2021, 9:43:11 PM] [SwitchBot] Unable to retreive device status.
[1/13/2021, 9:43:11 PM] [SwitchBot] deviceStatus - Hub {"statusCode":100,"body":{},"message":"success"}
```

**Comment by donavanbecker** [comment]
@pulkitjalan Yes that will be for volume control.

**Comment by pulkitjalan** [comment]
Cool, looks great! Thanks!

--
Pulkit Jalan
pulkit1990@gmail.com

**Comment by donavanbecker** [comment]
Ok @pulkitjalan, I got pretty far. 
- I have the volume control working in control center so if you go into control center and click the remote, you should see your TV you won't be able to use any of the buttons on the remote but of you move your volume up and down on your phone that should control your TV.
- Also I have On and Off, some what work. This is hard since with IR the power signal could get out of sync.

So if you could try the latest beta and give me feedback let me know.
Beta: `v1.2.5-beta.2`

**Comment by pulkitjalan** [comment]
On and Off works great, I can now see and control it from the home app as expected!

I tried the volume controls via the remote app and it kinda works. I had some inconsistent results, the volume would increase with the first press then decrease with the next press (pressing the same volume up button). It was the same with volume down. I tried again after turning the tv off and back on, and this time it was turning the tv off when pressing volume up.

The On Off feature works great though, thanks!

**Comment by pulkitjalan** [comment]
Logs:

```
- Pressing power in the home app
[1/14/2021, 8:26:45 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: turnOn parameter: default commandType: command

- Switching to control center and pressing volume up
[1/14/2021, 8:26:50 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command
[1/14/2021, 8:26:50 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: turnOn parameter: default commandType: command

- Pressing volume up again
[1/14/2021, 8:26:57 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command

- Pressing volume up again
[1/14/2021, 8:26:57 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command

- Pressing volume down
[1/14/2021, 8:27:08 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeAdd parameter: default commandType: command

- Pressing volume down again
[1/14/2021, 8:27:08 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command

- Pressing volume down again
[1/14/2021, 8:27:09 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command

- Waiting 1 minute and then pressing volume up in control center
[1/14/2021, 8:28:37 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command
[1/14/2021, 8:28:37 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: turnOn parameter: default commandType: command

- Pressing volume up again
[1/14/2021, 8:28:47 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command

- Pressing volume up again
[1/14/2021, 8:28:48 AM] [SwitchBot] Sending request for Bedroom TV TV to SwitchBot API. command: volumeSub parameter: default commandType: command
```

**Comment by Kohle81** [comment]
Hello @donavanbecker 

You are doing great work! Thank you first at all........

Yesterday I added the config manually and the Bots are working!

Now I installed the plugin sudo npm install -g --unsafe-perm homebridge-switchbot-openapi@1.2.5-beta.2 and started my Homebridge with this logs:

`Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"statusCode":100,"body":{"deviceList":[{"deviceId":"C42F040FCCD2","deviceName":"Bett Nicki hoch","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"},{"deviceId":"C9A1CF72C9FC","deviceName":"Bett Manu runter","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"},{"deviceId":"CBA415F0A044","deviceName":"Bett Manu hoch","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"},{"deviceId":"FD6A96EC2808","deviceName":"Hub Mini 08","deviceType":"Hub Mini","hubDeviceId":"000000000000"},{"deviceId":"FEDAC1EDB7BD","deviceName":"Bett Nicki runter","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"}],"infraredRemoteList":[{"deviceId":"02-202009290754-73988876","deviceName":"Haier TV","remoteType":"DIY TV","hubDeviceId":"FD6A96EC2808"}]},"message":"success"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Total Devices Found: 5
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"C42F040FCCD2","deviceName":"Bett Nicki hoch","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Discovered Bett Nicki hoch Bot
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Restoring existing accessory from cache: Bett Nicki hoch Bot DeviceID: C42F040FCCD2
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"C9A1CF72C9FC","deviceName":"Bett Manu runter","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Discovered Bett Manu runter Bot
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Restoring existing accessory from cache: Bett Manu runter Bot DeviceID: C9A1CF72C9FC
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"CBA415F0A044","deviceName":"Bett Manu hoch","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Discovered Bett Manu hoch Bot
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Restoring existing accessory from cache: Bett Manu hoch Bot DeviceID: CBA415F0A044
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"FD6A96EC2808","deviceName":"Hub Mini 08","deviceType":"Hub Mini","hubDeviceId":"000000000000"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Discovered a Hub Mini
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"FEDAC1EDB7BD","deviceName":"Bett Nicki runter","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"FD6A96EC2808"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Discovered Bett Nicki runter Bot
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Restoring existing accessory from cache: Bett Nicki runter Bot DeviceID: FEDAC1EDB7BD
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] {"deviceId":"02-202009290754-73988876","deviceName":"Haier TV","remoteType":"DIY TV","hubDeviceId":"FD6A96EC2808"}
Jan 14 21:04:53 raspberrypi homebridge[7876]: [14/01/2021, 21:04:53] [SwitchBot] Device: Haier TV with Device Type: DIY TV, is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
Jan 14 21:04:54 raspberrypi homebridge[7876]: [14/01/2021, 21:04:54] [SwitchBot] deviceStatus - Haier TV "wrong deviceId"
Jan 14 21:04:54 raspberrypi homebridge[7876]: [14/01/2021, 21:04:54] [SwitchBot] Unable to retreive device status.
Jan 14 21:04:54 raspberrypi homebridge[7876]: [14/01/2021, 21:04:54] [SwitchBot] deviceStatus - Bett Nicki runter {"statusCode":100,"body":{"deviceId":"FEDAC1EDB7BD","deviceType":"Bot","hubDeviceId":"FD6A96EC2808","power":"on"},"message":"success"}
Jan 14 21:04:55 raspberrypi homebridge[7876]: [14/01/2021, 21:04:55] [SwitchBot] deviceStatus - Hub Mini 08 {"statusCode":100,"body":{},"message":"success"}
Jan 14 21:05:00 raspberrypi homebridge[7876]: [14/01/2021, 21:05:00] [SwitchBot] deviceStatus - Bett Manu runter {"statusCode":100,"body":{"deviceId":"C9A1CF72C9FC","deviceType":"Bot","hubDeviceId":"FD6A96EC2808","power":"on"},"message":"success"}
Jan 14 21:05:00 raspberrypi homebridge[7876]: [14/01/2021, 21:05:00] [SwitchBot] deviceStatus - Bett Manu hoch {"statusCode":100,"body":{"deviceId":"CBA415F0A044","deviceType":"Bot","hubDeviceId":"FD6A96EC2808","power":"on"},"message":"success"}
Jan 14 21:05:02 raspberrypi homebridge[7876]: [14/01/2021, 21:05:02] [SwitchBot] deviceStatus - Bett Nicki hoch {"statusCode":100,"body":{"deviceId":"C42F040FCCD2","deviceType":"Bot","hubDeviceId":"FD6A96EC2808","power":"on"},"message":"success"}

`

I want to integrate the Infrared device "Haier TV" to HomeKit. What have I do in config?

**Comment by donavanbecker** [comment]
@Kohle81, I am releasing v2.0.0 right now. so just update to that and you should be good.

**Comment by donavanbecker** [comment]
@pulkitjalan I have fixed the issues and will be releasing v2.0.0 right now. pay attention to the ChangeLog!!!

**Comment by Kohle81** [comment]
Thanks for this and for fast answer.

Greetings from Germany

**Comment by Kohle81** [comment]
Hi, I‘m on version 2.0.0 now an I am getting this log:

Jan 14 23:05:22 raspberrypi homebridge[13767]: [14/01/2021, 23:05:22] [SwitchBot] {"deviceId":"02-202009290754-73988876","deviceName":"Haier TV","remoteType":"DIY TV","hubDeviceId":"FD6A96EC2808"}
Jan 14 23:05:22 raspberrypi homebridge[13767]: [14/01/2021, 23:05:22] [SwitchBot] Device: Haier TV with Device Type: DIY TV, is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] deviceStatus - Hub Mini 08 {"statusCode":100,"body":{},"message":"success"}
Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] deviceStatus - Haier TV "wrong deviceId"
Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] Unable to retreive device status.



The IR signal for Haier TV was learning by scanning remote signal. Is there a problem, if TV is a „self learned IR device“?

**Comment by donavanbecker** [comment]
> Hi, I‘m on version 2.0.0 now an I am getting this log:
> 
> ```
> Jan 14 23:05:22 raspberrypi homebridge[13767]: [14/01/2021, 23:05:22] [SwitchBot] {"deviceId":"02-202009290754-73988876","deviceName":"Haier TV","remoteType":"DIY TV","hubDeviceId":"FD6A96EC2808"}
> Jan 14 23:05:22 raspberrypi homebridge[13767]: [14/01/2021, 23:05:22] [SwitchBot] Device: Haier TV with Device Type: DIY TV, is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
> Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] deviceStatus - Hub Mini 08 {"statusCode":100,"body":{},"message":"success"}
> Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] deviceStatus - Haier TV "wrong deviceId"
> Jan 14 23:05:23 raspberrypi homebridge[13767]: [14/01/2021, 23:05:23] [SwitchBot] Unable to retreive device status.
> ```
> 
> The IR signal for Haier TV was learning by scanning remote signal. Is there a problem, if TV is a „self learned IR device“?

can you take a screenshot of your switchbot app? because it is self learned I might have to add another device type for TV, right now my device type is showing up as `TV`, and yours is showing up as DIY TV.

@Kohle81, Please fill out a feature request, like it says in the logs and we can work on this.

**Comment by Kohle81** [comment]
Thanks, I have created a feature request. I hope I‘m doing right

**Comment by donavanbecker** [comment]
@pulkitjalan How is v2.0.0 working?

**Comment by pulkitjalan** [comment]
Just upgraded to v2.0.0 @donavanbecker, and it works perfectly now, thanks a lot for all your work on this!!

**Comment by donavanbecker** [comment]
> Just upgraded to v2.0.0 @donavanbecker, and it works perfectly now, thanks a lot for all your work on this!!

Awesome! Sorry about the clearing of cache. I had to do it earlier then later, or more people would have a big issue.

**Comment by pulkitjalan** [comment]
@donavanbecker I seem to having a weird issue, not sure if its a bug or expected. I didnt have this in the morning when I first tested it.

```
Sent on command:
[1/15/2021, 4:45:30 PM] [SwitchBot] 1
[1/15/2021, 4:45:30 PM] [SwitchBot] Sending request for Bedroom 1 Tv TV to SwitchBot API. command: turnOn parameter: default commandType: command

Sent on command:
[1/15/2021, 4:45:40 PM] [SwitchBot] 1

Sent on command:
[1/15/2021, 4:45:43 PM] [SwitchBot] 1

Sent on command:
[1/15/2021, 4:45:47 PM] [SwitchBot] 1

Sent on command:
[1/15/2021, 4:45:55 PM] [SwitchBot] 1

Sent off command:
[1/15/2021, 4:46:02 PM] [SwitchBot] 0
[1/15/2021, 4:46:02 PM] [SwitchBot] Sending request for Bedroom 1 Tv TV to SwitchBot API. command: turnOff parameter: default commandType: command

Sent off command:
[1/15/2021, 4:46:07 PM] [SwitchBot] 0
[1/15/2021, 4:46:07 PM] [SwitchBot] Sending request for Bedroom 1 Tv TV to SwitchBot API. command: turnOff parameter: default commandType: command

Sent off command:
[1/15/2021, 4:46:10 PM] [SwitchBot] 0
[1/15/2021, 4:46:10 PM] [SwitchBot] Sending request for Bedroom 1 Tv TV to SwitchBot API. command: turnOff parameter: default commandType: command

Sent on command:
[1/15/2021, 4:46:15 PM] [SwitchBot] 1
[1/15/2021, 4:46:15 PM] [SwitchBot] Sending request for Bedroom 1 Tv TV to SwitchBot API. command: turnOn parameter: default commandType: command

Sent on command:
[1/15/2021, 4:46:30 PM] [SwitchBot] 1

Sent on command:
[1/15/2021, 4:46:35 PM] [SwitchBot] 1

Sent on command:
[1/15/2021, 4:46:38 PM] [SwitchBot] 1
```

From the above logs, when sending repeat `turn on` commands, it prints a 1 but not actually sending the command, however for `turn off` it seems to be working as before.

**Comment by donavanbecker** [comment]
@pulkitjalan let me test a little bit. I think that was left behind logging for testing. I have it set so that if it is on, that it doesn't send another on because if I did then it would turn off because of how the ir power button works.

**Comment by pulkitjalan** [comment]
I see, any way to switch that functionality off? Since it gets out of sync sometimes, it was a good way to basically sync up the state again.

**Comment by donavanbecker** [comment]
> I see, any way to switch that functionality off? Since it gets out of sync sometimes, it was a good way to basically sync up the state again. 

If I turn that off then we would be back to where we were before where if the tv is on and you try to control the tv from control center, then it will turn it off because it sends the on command before controlling anything in control center, since control center doesn't know if it is on or not.

**Comment by pulkitjalan** [comment]
Oh ok, I didn’t realise that was linked. Ok no worries 👍

--
Pulkit Jalan
pulkit1990@gmail.com
