### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by virtualxdriver** [OpenWonderLabs/homebridge-switchbot-openapi#43]
**Is your feature request related to a problem? Please describe.**

See #42. API calls are suddenly failing with a 401 Unauthorized error, but switches in HomeKit seem to behave correctly.

**Describe the solution you'd like**

When a call to the API fails, the exception should surface to HomeKit and the button display an error sign to alert the user.

**Describe alternatives you've considered**

The alternative plugin homekit-switchbot-for-mac handles timeout errors and only triggers the state change of the button when the call actually made it.

**Additional context**

None.

**Comment by donavanbecker** [comment]
@virtualxdriver I need more info about your setup, how your config is setup, etc.

**Comment by thehilsnz** [comment]
FYI I’ve started seeing the same issue today as well - after adding the bots in - I have 2 curtain groups (4 curtain devices - of which I’ve now hidden the 2 slaves), and 3 bots (as well as 2 hubs and a sensor which aren’t technically in the HomeKit config). I’ve set the refresh rate to 800, but  guessing I have to wait until tomorrow and my limit resets.
