### ISSUE TITLE
Automatically hide secondary Curtain on grouped SwitchBot Curtains

### ISSUE THREAD

**Issue by FishyD** [OpenWonderLabs/homebridge-switchbot-openapi#48]
**Describe The Bug:**

I have 2 SwitchBot Curtains paired together in the SwitchBot App as left and right sides. However, when adding them to the Home app via this plug-in, both appear in the home app and the Homebridge Accessories part of the Homebridge UI. One is the "grouped" curtains and this one operates both sides as desired. The other curtain is the right side and is non-responsive.

**To Reproduce:**

Group 2 SwitchBot curtains together as left and right sides. Then add these to the plug-in/Home app.

**Expected behavior:**

For curtains grouped in the SwitchBot app, only the group should populate in the Homebridge Accessories tab and iOS home app.

**Logs:**

```
I opened/closed both the working group and the "right" curtain in the log below:
[1/13/2021, 5:47:58 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[1/13/2021, 5:47:58 PM] Got SIGTERM, shutting down Homebridge...
[1/13/2021, 5:48:03 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/13/2021, 5:48:08 PM] [HB Supervisor] Restarting Homebridge...
[1/13/2021, 5:48:08 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/13/2021, 5:48:08 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 2206
[1/13/2021, 5:48:10 PM] Loaded config.json with 0 accessories and 2 platforms.
[1/13/2021, 5:48:10 PM] ---
[1/13/2021, 5:48:12 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/13/2021, 5:48:12 PM] Registering platform 'homebridge-config-ui-x.config'
[1/13/2021, 5:48:12 PM] ---
[1/13/2021, 5:48:12 PM] The plugin "homebridge-switchbot-openapi" requires Node version of >=14.15.3 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.
[1/13/2021, 5:48:12 PM] Loaded plugin: homebridge-switchbot-openapi@1.2.4
[1/13/2021, 5:48:12 PM] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
[1/13/2021, 5:48:12 PM] ---
[1/13/2021, 5:48:12 PM] Loading 2 platforms...
[1/13/2021, 5:48:12 PM] [Config] Initializing config platform...
[1/13/2021, 5:48:12 PM] [Config] Running in Service Mode
[1/13/2021, 5:48:12 PM] [SwitchBot] Initializing SwitchBot platform...
[1/13/2021, 5:48:12 PM] [SwitchBot] Using Default Refresh Rate.
Setup Payload:
X-HM://DELETED
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

┌────────────┐     
│ DELETED 
└────────────┘     
[1/13/2021, 5:48:12 PM] Homebridge is running on port DELETED.
[1/13/2021, 5:48:13 PM] [SwitchBot] Total Devices Found: 4
[1/13/2021, 5:48:13 PM] [SwitchBot] Discovered Right Office Curtain
[1/13/2021, 5:48:13 PM] [SwitchBot] Adding new accessory: Right Office Curtain DeviceID: DELETE
[1/13/2021, 5:48:13 PM] [SwitchBot] Discovered Office Curtains Curtain
[1/13/2021, 5:48:13 PM] [SwitchBot] Adding new accessory: Office Curtains Curtain DeviceID: DELETE
[1/13/2021, 5:48:13 PM] [SwitchBot] Discovered a Hub Mini
[1/13/2021, 5:56:03 PM] [SwitchBot] Sending request for Office Curtains Curtain to SwitchBot API. command: setPosition parameter: 0,ff,100 commandType: command
[1/13/2021, 5:56:20 PM] [SwitchBot] Sending request for Office Curtains Curtain to SwitchBot API. command: setPosition parameter: 0,ff,0 commandType: command
```

**Homebridge Config:**

```
{
"bridge": {
"name": "Homebridge",
"username": "DELETED",
"port": DELETED,
"pin": "DELETED"
},
"accessories": [],
"platforms": [
{
"name": "Config",
"port": DELETED,
"platform": "config"
},
{
"name": "SwitchBot",
"credentials": {
"openToken": "DELETED",
"notice": "Keep your token a secret!"
},
"platform": "SwitchBot"
}
]
}
```

**Screenshots:**

![IMG_89F4DE723EA7-1](https://user-images.githubusercontent.com/26522740/104520997-16d8e500-55ca-11eb-8cbe-c87a0e2e6742.jpeg)
![IMG_2CD357ADBCE7-1](https://user-images.githubusercontent.com/26522740/104521004-193b3f00-55ca-11eb-87e1-7fb1dbdc986b.jpeg)

**Device Model:**

Raspberry PI (Homebridge UI), multiple iOS devices. 

# **Environment:**

- **Node.js Version**: 14.15.1
- **NPM Version**: current (update ran)
- **Homebridge Version**: 1.1.7
- **Homebridge SwitchBot Plugin Version**: 1.2.4
- **Homebridge Config UI X Plugin Version**: 4.36.1
- **Operating System**:

**Comment by donavanbecker** [comment]
@FishyD, yeah currently the API shows if they are grouped or not, but if I push a change to the API, it doesn't psh the change to both.

I will submit a feature request with SwitchBot to see if something can change with this. Currently my curtains are ungrouped because of this reason.

**Comment by FishyD** [comment]
@donavanbecker Makes sense, thank you. For now, I used the plug-in’s advanced setting for hide device by device id. I hid the extra curtain and nothing seems to have broken. Seems like a good workaround for now.

**Comment by donavanbecker** [comment]
> @donavanbecker Makes sense, thank you. For now, I used the plug-in’s advanced setting for hide device by device id. I hid the extra curtain and nothing seems to have broken. Seems like a good workaround for now. 

Are commands working as expected? Like if you close the main curtain, it closes the group?

**Comment by FishyD** [comment]
@donavanbecker Yes, both bots open and close in sync even with the right bot hidden. In the SwitchBot app, when you make a group originally, it appears to make the first curtain bot (in my case left) the master and then kind of hides the second (in my case right) during the grouping process.

The plugin appears to be showing both the "master" left bot which is essentially controlling both, and the right one which does nothing (and hidden in the SB app). It isn't truly ungrouping them which would break the sync and calibration between the two. Hiding the right bot by device id appears to have no impact on the grouped left/master control. Clicking open on the curtain (in the home app) opens both and maintains open/close calibration of both bots as established in the SB app.

**Comment by jonpeng** [comment]
I did the same thing by hiding the device IDs in the plugin advanced setting. Homekit accessories look good and work good. No issues.

**Comment by donavanbecker** [comment]
@FishyD and @jonpeng I think this is going to have to be our solution until an API change happens. I am going to leave this Issue open until then.

**Comment by VeniceNerd** [comment]
I have the same issue! Do you know how I can figure out the ID of my “phantom” bot? It seems hidden in the app now. 

I would like to hide it.

**Comment by FishyD** [comment]
I found it in the log, back when I originally added the plug-in to my HomeBridge. Perhaps there is another way?

**Comment by donavanbecker** [comment]
> I have the same issue! Do you know how I can figure out the ID of my “phantom” bot? It seems hidden in the app now.
> 
> I would like to hide it.

@VeniceNerd are you talking about your curtain? or your bot?

Every device that is found will print the device id in the log.

Example:
```
Restoring existing accessory from cache: Bathroom DIY Fan DeviceID: 12-345678910111-213141516
```

**Comment by donavanbecker** [comment]
> I found it in the log, back when I originally added the plug-in to my HomeBridge. Perhaps there is another way?

you can look for your Mac address in the SwitchBot app and take out the `:` (colons)

**Comment by Aekung** [comment]
Hiding one bot and only use the priority bot doesn't really work in my case. It would work for a day, then it would only control the priority bot the next day without trying to move the secondary bot. This causes the curtain to not being able to fully open or close since the secondary bot's motor doesn't work so it doesn't help running on the track together with the priority bot hence the curtain becomes too heavy for the priority bot to open or close on its own.

**Comment by FishyD** [comment]
> Hiding one bot and only use the priority bot doesn't really work in my case. It would work for a day, then it would only control the priority bot the next day without trying to move the secondary bot. This causes the curtain to not being able to fully open or close since the secondary bot's motor doesn't work so it doesn't help running on the track together with the priority bot hence the curtain becomes too heavy for the priority bot to open or close on its own.

I don’t think you are using the two bots like we are. We are using them as pairs to manipulate opposing sides of a left/right curtain. It seems you are trying to use them as a train, to open a heavy curtain. I’m
not tracking that is a configuration supported by the SB app. Am I understanding correctly? 

If you pair 2 bots properly in the SB app: You have to hide the bot you added second when you setup the pair in the SB app. Using the method described above I have hidden the second curtain on 3 paired curtain setups and it has been working flawlessly on a daily basis since the day I posted above. Does it work properly in the SwitchBot app?

**Comment by Aekung** [comment]
> > Hiding one bot and only use the priority bot doesn't really work in my case. It would work for a day, then it would only control the priority bot the next day without trying to move the secondary bot. This causes the curtain to not being able to fully open or close since the secondary bot's motor doesn't work so it doesn't help running on the track together with the priority bot hence the curtain becomes too heavy for the priority bot to open or close on its own.
> 
> I don’t think you are using the two bots like we are. We are using them as pairs to manipulate opposing sides of a left/right curtain. It seems you are trying to use them as a train, to open a heavy curtain. I’m
> not tracking that is a configuration supported by the SB app. Am I understanding correctly?
> 
> If you pair 2 bots properly in the SB app: You have to hide the bot you added second when you setup the pair in the SB app. Using the method described above I have hidden the second curtain on 3 paired curtain setups and it has been working flawlessly on a daily basis since the day I posted above. Does it work properly in the SwitchBot app?

I am sure that I pair 2 bots properly in SB app. It works now for some reason but, sometimes, the opening or closing status will always say "closing or opening" nonstop (Only sometimes). Is it also happening to you?

**Comment by donavanbecker** [comment]
> > > Hiding one bot and only use the priority bot doesn't really work in my case. It would work for a day, then it would only control the priority bot the next day without trying to move the secondary bot. This causes the curtain to not being able to fully open or close since the secondary bot's motor doesn't work so it doesn't help running on the track together with the priority bot hence the curtain becomes too heavy for the priority bot to open or close on its own.
> > 
> > 
> > I don’t think you are using the two bots like we are. We are using them as pairs to manipulate opposing sides of a left/right curtain. It seems you are trying to use them as a train, to open a heavy curtain. I’m
> > not tracking that is a configuration supported by the SB app. Am I understanding correctly?
> > If you pair 2 bots properly in the SB app: You have to hide the bot you added second when you setup the pair in the SB app. Using the method described above I have hidden the second curtain on 3 paired curtain setups and it has been working flawlessly on a daily basis since the day I posted above. Does it work properly in the SwitchBot app?
> 
> I am sure that I pair 2 bots properly in SB app. It works now for some reason but, sometimes, the opening or closing status will always say "closing or opening" nonstop (Only sometimes). Is it also happening to you?

You will want to set your min and max, because API doesn't say close or open like SwitchBot App, this is the only way to get around this. As you can see I have mine set 2 and 98.
<img width="760" alt="Screen Shot 2021-02-07 at 9 55 00 PM" src="https://user-images.githubusercontent.com/9875439/107174180-2c55ea80-698f-11eb-872b-d136289b3531.png">

**Comment by Aekung** [comment]
> > > > Hiding one bot and only use the priority bot doesn't really work in my case. It would work for a day, then it would only control the priority bot the next day without trying to move the secondary bot. This causes the curtain to not being able to fully open or close since the secondary bot's motor doesn't work so it doesn't help running on the track together with the priority bot hence the curtain becomes too heavy for the priority bot to open or close on its own.
> > > 
> > > 
> > > I don’t think you are using the two bots like we are. We are using them as pairs to manipulate opposing sides of a left/right curtain. It seems you are trying to use them as a train, to open a heavy curtain. I’m
> > > not tracking that is a configuration supported by the SB app. Am I understanding correctly?
> > > If you pair 2 bots properly in the SB app: You have to hide the bot you added second when you setup the pair in the SB app. Using the method described above I have hidden the second curtain on 3 paired curtain setups and it has been working flawlessly on a daily basis since the day I posted above. Does it work properly in the SwitchBot app?
> > 
> > 
> > I am sure that I pair 2 bots properly in SB app. It works now for some reason but, sometimes, the opening or closing status will always say "closing or opening" nonstop (Only sometimes). Is it also happening to you?
> 
> You will want to set your min and max, because API doesn't say close or open like SwitchBot App, this is the only way to get around this. As you can see I have mine set 2 and 98.
> <img alt="Screen Shot 2021-02-07 at 9 55 00 PM" width="760" src="https://user-images.githubusercontent.com/9875439/107174180-2c55ea80-698f-11eb-872b-d136289b3531.png">

Still doesn't work correctly for me. Today, it seems to be getting worst. Homekit today only commands a single bot, not both, for no reason.

I checked that the Switchbot app is still pairing in "Both Sides" mode and the switchbot remote I have is working correctly. Only the Homekit commands that wouldn't be registered the right way somehow.

This is very frustrated since the Switchbot and Switchbot Humidifier work very well with the plugin. Only the curtain that is not really working.

Any suggestion on this?

**Comment by donavanbecker** [comment]
@Aekung can you Please open a new issue and we can track your issue with curtains there?

**Comment by donavanbecker** [comment]
@FishyD @VeniceNerd @jonpeng

I believe I have a fix for this in the latest beta if you could give it a test and let me know if it works for you.

Beta:  `v3.0.2-beta.0`

The way this should work, The API gives a `curtainDevicesIds` Array which as 2 `deviceIds` when grouped. The plugin looks at the first `deviceId` in the `curtainDevicesIds` Array and added it, and ignores the other device id. 

So in theory, you can remove the `deviceID` that you hid using the hide deviceId feature and once you restart, that device should stay hidden. Let me know if this does or doesn't work for you.

**Comment by FishyD** [comment]
@donavanbecker Sure, I would be happy to. How do I get the beta? I can't find it in versions tab or in app.

**Comment by donavanbecker** [comment]
@FishyD 

Install:

```
sudo npm install -g --unsafe-perm homebridge-SwitchBot-openapi@beta
```

Revert:

```
sudo npm install -g --unsafe-perm homebridge-SwitchBot-openapi@latest
```

**Comment by FishyD** [comment]
@donavanbecker Getting errors in terminal. 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-SwitchBot-openapi - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-SwitchBot-openapi@beta' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters

Drop the capital "S"?

**Comment by donavanbecker** [comment]
@FishyD yes sorry, it auto capitalized

**Comment by FishyD** [comment]
@donavanbecker 3.0.3 works perfectly. It automatically hides the slaved bot and keeps the master displayed.

**Comment by donavanbecker** [comment]
@FishyD should I add a log letting the user know that a group device has been found and that the secondary device has been grouped/hidden?

**Comment by FishyD** [comment]
@FishyD I think it would certainly help let folks know what is going on behind the scenes when you add a grouped device.

**Comment by Aekung** [comment]
Happy to report that the 3.0.3 Beta also works very fine for me. All the problem I have got on the previous version are gone, at least for now.

Thank you very much.

**Comment by mayhew132** [comment]
Just in case anyone like me has an extra 'C9 Curtain' appearing on their HomeKit setup and wants to know where to put the 'device ID' in Hoobs so that it is removed see below for a screen grab on where you should put the Device ID, surrounded by double quotes:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/25966969/113699662-c905e180-96cd-11eb-8d00-bc1562a98cbd.png">

**Comment by donavanbecker** [comment]
@mayhew132 , I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by mayhew132** [comment]
> @mayhew132 , I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

Thanks - I used to use HomeBridge, but moved to Hoobs in a Docker image as I find GUI's easier to use (I used to break my HomeBridge install by using the wrong bash commands!)

**Comment by donavanbecker** [comment]
@mayhew132 Homebridge does have a UI

**Comment by mayhew132** [comment]
Thanks - I'll have a look if I come across any problems with Hoobs!
