### ISSUE TITLE
401 Error Status Code

### ISSUE THREAD

**Issue by nyjklein** [OpenWonderLabs/homebridge-switchbot-openapi#57]
Started getting status code 401 errors this morning

I tried opening this as a bug report, but it didn't like the format. I tried using the template.
Logs:

Started getting this every two minutes
```
[16/01/2021, 09:35:43] [SwitchBot] Meter - Failed to update status of Living Room Meter "Request failed with status code 401" undefined
[16/01/2021, 09:37:43] [SwitchBot] Meter - Failed to update status of Living Room Meter "Request failed with status code 401" undefined
[16/01/2021, 09:37:43] [SwitchBot] Curtain - Failed to refresh status of Living Room Curtain "Request failed with status code 401" undefined

Then after restart, just got this:
[16/01/2021, 10:27:50] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
```

Homebridge Config:
```
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "***",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 120,
                "hide_device": [
                    "***"
                ],
                "curtain": {
                    "set_minStep": 3
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        }
```

Screenshots:

Device Model:

Environment:
Node.js Version | v14.15.4:
Npm Version | v6.14.10:
Homebridge v1.1.7:
homebridge-switchbot-openapi v2.0.0:
homebridge-config-ui-x v4.36.0:
Raspbian:

**Comment by donavanbecker** [comment]
@nyjklein you changed to much to the issue template...

**Comment by nyjklein** [comment]
I've attached my config here. Also, since the API doc shows 401 is an invalid token, I regenerated my token but I'm still getting this.

{
    "bridge": {
        "name": "Homebridge BFAB",
        "username": "***",
        "port": 51567,
        "pin": "***"
    },
    "accessories": [
        {
            "name": "Pseudo Hallway",
            "delay": 300000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Pseudo 1 Minute",
            "delay": 60000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Pseudo 10 Minute",
            "delay": 600000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Pseudo 5 Second",
            "delay": 5000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Psuedo Enytryway",
            "delay": 300000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Pseudo Kitchen",
            "delay": 360000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "accessory": "CmdTrigger",
            "name": "Hello World",
            "command": "echo Hello World",
            "delay": "10000",
            "execAfterDelay": false
        },
        {
            "accessory": "CmdTrigger",
            "name": "HB Restart",
            "command": "sudo -n systemctl restart homebridge",
            "delay": "10000",
            "execAfterDelay": false
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Nest",
           REMOVED
            },
            "options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "HomeAway.Disable"
            ],
            "platform": "Nest"
        },
        {
            "bonds": [
                {
                    "ip_address": "***",
                    "token": "***"
                }
            ],
            "include_dimmer": false,
            "include_toggle_state": false,
            "fan_speed_values": false,
            "platform": "Bond"
        },
        {
            "email": "nyjklein@panix.com",
            "password": "***",
            "refreshInterval": 12,
            "activeRefreshInterval": 3,
            "activeRefreshDuration": 300,
            "platform": "myQ"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "***",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 120,
                "hide_device": [
                    "***"
                ],
                "curtain": {
                    "set_minStep": 3
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        }
    ]
}

**Comment by donavanbecker** [comment]
@nyjklein Your refreshRate is at `120` you will need to move that up. Either remove and let plugin set default or go higher and see if your devices can handle it.

Pulling to many requests.

**Comment by nyjklein** [comment]
BTW, I did set "devicediscovery" to true. But it didn't generate any additional log entries. 

I changed refreshrate from the default yesterday and everything was fine until this morning. I'll set it back and see what happens.

**Comment by donavanbecker** [comment]
@nyjklein Once you set this, you will have to wait for the API to allow you to reconnect to it.

**Comment by nyjklein** [comment]
Back to the default (300). Restarted and still got the 401 on discovery. Do you know how long it will be before it lets me back in? Will it happen spontaneously or will I need to restart periodically?

Thanks for the plugin and your help!

Jeff

**Comment by donavanbecker** [comment]
> BTW, I did set "devicediscovery" to true. But it didn't generate any additional log entries. 
> 
> 
> 
> I changed refreshrate from the default yesterday and everything was fine until this morning. I'll set it back and see what happens.

If I may ask why did you set `devicediscovery`?

**Comment by Bgoshua** [comment]
@nyjklein Fwiw I went through my logs after this happened to me and it took around 12 hours for the api to allow reconnect

**Comment by donavanbecker** [comment]
> Back to the default (300). Restarted and still got the 401 on discovery. Do you know how long it will be before it lets me back in? Will it happen spontaneously or will I need to restart periodically?
> 
> 
> 
> Thanks for the plugin and your help!
> 
> 
> 
> Jeff
> 
> 

When I first received a 401 it took about a half a day I would say, but might not be back till tomorrow. Sorry....
I would wait till then to restart so that you aren't requesting anymore.

**Comment by nyjklein** [comment]
> > BTW, I did set "devicediscovery" to true. But it didn't generate any additional log entries.
> > I changed refreshrate from the default yesterday and everything was fine until this morning. I'll set it back and see what happens.
> 
> If I may ask why did you set `devicediscovery`?
When the errors started, I thought this might generate additional information and the bug report template suggested it.

**Comment by donavanbecker** [comment]
> When the errors started, I thought this might generate additional information and the bug report template suggested it.
> 
> 

Thanks for letting me know why. I will remove it from the big report template. Sorry for this issue auto closing on you. 

In the future just add info, never take away or it will auto close. I put this in place so spam issues auto close.

**Comment by nyjklein** [comment]
I'm back in action this morning.

**Comment by donavanbecker** [comment]
@nyjklein Awesome!!
