### ISSUE TITLE
Please add support for A/C

### ISSUE THREAD

**Issue by amanolo** [OpenWonderLabs/homebridge-switchbot-openapi#69]
{
	"statusCode":100,
	"body":	{
		"deviceList": [
			],
			"infraredRemoteList": [
					{
						"deviceId": "02-202101201235-11403291",
						"deviceName": "Living Room Air Conditioner",
						"remoteType":"Air Conditioner",
						"hubDeviceId":"EEDA097901BD"
					}
			]
	},
	"message":"success"
}

**Comment by donavanbecker** [comment]
As you probably already know, this has been released with v2.1.0
