### ISSUE TITLE
Meter - F vs. C

### ISSUE THREAD

**Issue by nyjklein** [OpenWonderLabs/homebridge-switchbot-openapi#98]
Describe The Bug:
I upgraded to 2.4.0 this morning which added the meter option to convert to F or C. I selected F and boy it got really hot 159 degrees! :)

I'm not sure it's a bug or just a documentation clarification. The Homebridge-Config-UI-X has it's own F vs. C option that was already converting for me. So selecting F in the switchbot plugin ended up doing a double conversion.

To Reproduce:
Set the temperature option in the homebridge UI and then set it in the switchbot plugin, 

Expected behavior:
I guess don't convert in the switchbot plugin if the homebridge-ui has the same setting.

**Logs:
**

***Read and Paste over this Text the Text Above^^^^^^
Excerpts from Homebridge Config:

{
    "bridge": {
        "name": "Homebridge BFAB",
        "username": "xxx",
        "port": 51567,
        "pin": "xxx"
    },
    "accessories": [
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": xxxxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "xxx"
                ],
                "meter": {
                    "unit": 1
                },
                "humidifier": {
                    "hide_temperature": true,
                    "set_minStep": 33
                },
                "curtain": {
                    "set_minStep": 20,
                    "set_min": 3,
                    "set_max": 97
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        },    ]
}
***Read and Paste over this Text the Text Above^^^^^^
Screenshots:

Device Model:

Environment:
Node.js Version: v14.15.4:
NPM Version: v7.5.2:
Homebridge Version: v1.1.7:
Homebridge SwitchBot Plugin Version: v2.4.0:
Homebridge Config UI X Plugin Version: v4.38.0:
Operating System: Raspbian:

**Comment by donavanbecker** [comment]
@nyjklein its only for converting purposes if you need to, I added it just incase someones temperature wasn't showing correctly.

**Comment by nyjklein** [comment]
Thanks. That's fine. Was just letting you know.

**Comment by donavanbecker** [comment]
@nyjklein thanks! yeah I could potentially add more documentation. It might be something not needed but wasn't sure.

Also the Homebridge UI, Fahrenheit and Celsius, doesn't have an impact on plugins so I think that it is just something the home app is converting which I am kinda surprised by...
